### PR TITLE
Bump to 2.1.4 spring-boot-starter-parent

### LINKED ISSUE #78: spring-boot-maven-plugin:2.0.5.RELEASE  InvocationTargetException
The full error that I am getting when I run mvn clean spring-boot:run is:
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.0.5.RELEASE:run (default-cli) on project nonrest: An exception occurred while running. null: InvocationTargetException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException: javax.xml.bind.JAXBException -> [Help 1]

### PR DESCRIPTION
**Pull request by thrasymache**
This prevents InvocationTargetException in spring-boot-maven-plugin
Fixes #78

### CODE REVIEW

**Comment by gregturn** [comment]
Resolved via 3fc939c.

**Comment by gregturn** [comment]
Thanks @thrasymache for catching this. It appears I started in and patched the same thing.

**Comment by thrasymache** [comment]
You're very welcome, @gregturn - I'm happy to help. It's a good tutorial for a bunch of reasons and it would be a shame for others to get discouraged trying to get it to run.

**Comment by pivotal-issuemaster** [comment]
@thrasymache Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-rest&pullRequestId=79)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-rest&pullRequestId=79) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@thrasymache Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-rest&pullRequestId=79)!

**Pull request closed without merging**
