### PR TITLE
Upgrade to HATEOAS 1.0

### LINKED ISSUE #84: HATEOS related section of the tutorial is outdated
I had some touble working throught the part of the tutorial that had to do with the `spring-boot-starter-hateoas`. This dependency gets introduced in the "What makes something RESTful?" section.

It seems the code examples are based on an older version of this dependency.

Following the information [here](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#migrate-to-1.0) helped me get through the tutorial.

The tutorial itself was really nice.

### PR DESCRIPTION
**Pull request by yanwenkun**
Fixes #84 

This Pull Request consist of 3 major changes:

#### 1. Upgrade whole project to Spring Boot 2.2.2.RELEASE.

1.1. upgrade root POM's parent to `2.2.2.RELEASE`.
1.2. remove `spring-plugin-core` and `json-path` from root POM (bundled now).
1.3. remove `Spring Snapshot Repository` from root POM (no longer needed).
1.4. update sub-POMs' `h2` to be scoped at `runtime` (following Spring Initializr).
1.5. update sub-POMs' `lombok` to be `optional` (following Spring Initializr).
1.6. update `.gitignore` (following Spring Initializr).
1.7. all `Employee` class constructors are `public` now (following Intellij IDEA's advice).
1.8. upgrade `Maven Wrapper` to version 0.5.6.

#### 2. Refactor Java code to be compliant with [HATEOAS 1.0](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#migrate-to-1.0.changes).

2.1. using [migrate-to-1.0.sh](https://github.com/spring-projects/spring-hateoas/tree/master/etc).
2.2. replace `(assembler::toResource)` with `(assembler::toModel)`.
2.3. rename `EmployeeResourceAssembler.java`to `EmployeeModelAssembler.java`, `OrderResourceAssembler.java` to `OrderModelAssembler.java`.
2.4. change `created(URI)`'s parameter from `new URI(resource.getId().expand().getHref())` to `entityModel.getRequiredLink(IanaLinkRelations.SELF).toUri()`.

#### 3. Update `README.adoc` to match with the changes above.

3.1. replace all updated class names.
3.2. remove text ```And don't confuse `ResourceSupport.getId()` with `Employee.getId()`.```

All checked, should work just fine.

BTW, thx for this nice tutorial!

### CODE REVIEW

**Comment by yanwenkun** [comment]
@yahkun You are dealing with wrong version of Spring HATEOAS.
In 1.0, `org.springframework.hateoas.Resource` is **RENAMED**, and it's now `EntityModel`.
It looks like your Intellij IDEA is still using local cached version, try fix it by:
- Press `Ctrl + Shift + A` and search `Reimport All Maven Projects`

**Comment by yanwenkun** [comment]
@gregturn Hello Mr. Turnquist, would you please have a look on this pull request? Much appreciated!

**Comment by gregturn** [comment]
@yanwenkun Thanks for your efforts.

I've decided to go with #89 's modifications.

If you wish to skim over those results and see if there is other stuff to polish up, feel free.

**Comment by yanwenkun** [comment]
……After two and half months of being ignored, a new Pull Request suddenly showed up and get merged in less than two hours. That's something, NICE.

**Pull request closed without merging**
