### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by artisancreek**

### CODE REVIEW

**Comment by gregturn** [comment]
Can you rebased against the latest changes?

**Comment by artisancreek** [comment]
I rebased my fork. Fairly new to git specifics. If you need me to do something else, let me know. Thanks.

**Comment by gregturn** [comment]
After rebasing, you have to force-push your branch so this PR gets updated.

**Comment by artisancreek** [comment]
I have done the force-pushed. Please let me know if I need to do something else. Thank you.

**Pull request merged**
