### PR TITLE
Improvements from following along

### PR DESCRIPTION
**Pull request by UgmaDevelopment**
Hi!

I recently went through and followed this tutorial to its conclusion. Along the way, if I saw something that I found unclear or that could clearly be improved upon, I did my best to leave it better than I found it.

If you disagree with any of the changes, feel free to make suggestions for improvement and I'll see what I can do.

Thanks for the guide!

### CODE REVIEW

**Comment by gregturn** [comment]
@UgmaDevelopment This looks GREAT!

In light of recent updates to the project, would you be willing to rebase and squash your work into a single commit?

**Comment by UgmaDevelopment** [comment]
I've never done that before. Does it seem like I did it about right?

**Comment by gregturn** [comment]
Perfect!

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/tut-rest/commit/559cda5c3cfbebdd0e490aeb572a5d24330132d8.

**Comment by gregturn** [comment]
Thanks @UgmaDevelopment!

**Pull request closed without merging**
